### ISSUE TITLE
About your spatial templates 

### ISSUE THREAD

**Issue by zhangqianhui** [genforce/volumegan#1]
Thanks for your sharing paper. 

One question is how to init the spatial templates ?  Is it a 3D meshgrid or any prior distributions?

**Comment by justimyhxu** [comment]
I initialize the spatial templates with value one like StyleGAN.
You can refer [StyleGAN-tf](https://github.com/NVlabs/stylegan/blob/1e0d5c781384ef12b50ef20a62fee5d78b38e88f/training/networks_stylegan.py#L507) or [GenForce](https://github.com/genforce/genforce/blob/e3bc4b4b708ac72cd6155f3eda3463329e395cc8/models/stylegan_generator.py#L809).

**Comment by zhangqianhui** [comment]
ok, thanks.
